name: Test

on: [push, pull_request]

env:
  SCARB_VERSION: 2.4.0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: 0.14.0
      - name: Run cairo tests
        run: snforge test
